component: website
name: todos-frontend

inputs:
  src:
    src: ./
    hook: npm i && npm run build
    dist: ./build
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: todos-frontend
  protocol: https
  env:
    apiUrl: ${output:${stage}:${app}:todos-backend.apigw.url}
