component: http
name: todos-backend
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs14.18
    timeout: 100
    framework: koa
    name: ${name}
    installDependency: true
    vpc:
      vpcId: ${output:${stage}:${app}:todos-vpc.vpcId}
      subnetId: ${output:${stage}:${app}:todos-vpc.subnetId}
    environments:
      - key: dbConnUrl
        value: ${output:${stage}:${app}:todos-db.private.connectionString}
  apigw:
    api:
      cors: true
    protocols:
      - http
      - https
    environment: release
